config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root :to => 'top#show'
  resource :top, controller: :top, only: :show
  resource :home, controller: :home, only: :show
  resources :messages, only: [:index, :show, :new, :create]
  resources :receives, only: [:index, :show] do
    get :notify, on: :collection
    get :list, on: :collection
  end
  resource :guides, only: :show do
    get :start, on: :collection
  end
  resource :tutorial, controller: :tutorial, only: :show do
    get :confirm, on: :collection
    get :complete, on: :collection
  end
  
  devise_for :admins
  namespace :x do
    resource :home, controller: :home, only: :show
    resources :users, only: [:index, :show]
    resources :notifications, only: [:index, :show, :new, :create, :edit, :update]
    resources :messages, only: [:index, :edit, :update] do
      post :connect, on: :member
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :owner, class_name: 'User', foreign_key: "owner_id"
	has_many :senders, :dependent => :destroy
	has_many :users, :through => :senders
	belongs_to :reply_to, class_name: 'User', foreign_key: "reply_to"

	mount_uploader :address, MessageUploader
	mount_uploader :message, MessageUploader

	scope :notifications, -> { where("text IS NOT NULL") }
	scope :mails, -> { where("message IS NOT NULL")}

end

app/models/sender.rb
class Sender < ActiveRecord::Base
	belongs_to :user
	belongs_to :message
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :own_messages, class_name: 'Message', foreign_key: "owner_id"
	has_many :senders, :dependent => :destroy
	has_many :messages, :through => :senders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.options_for_select
    User.order(:id).collect do |usr|
      [usr.name, usr.id]
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  private

  def layout_by_resource
    return "top" if devise_controller?
    return "application"
  end

  def after_sign_in_path_for(resource)
    return guides_path if resource.is_a?(User)
    return x_messages_path if resource.is_a?(Admin)
  end

  def after_sign_out_path_for(resource)
    reset_session
    return root_path if resource == :user
    return root_path if resource == :admin
  end

end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
	layout "top"
	before_filter :authenticate_user!

  def show
  end

  def start
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "top"
	before_filter :authenticate_user!

  def show
  	@notifications = current_user.messages.notifications.order("id DESC")
  	@messages = current_user.messages.mails.order("id DESC")
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	layout "top"
  before_filter :authenticate_user!

  def index
  end

  def show
    @message = Message.find(params[:id])
  end
  
  def new
  	@message = Message.new
    @sender = User.find(params[:owner]) if params[:owner]
    if params[:reply]
      @sender = User.find(params[:reply])
      @reply = true
    end
  end

  def create
  	@message = current_user.own_messages.new(message_params)
    @message.users << User.find(params[:sender]) if params[:sender]
  	if @message.save
      if params[:reply].present?
    		redirect_to confirm_tutorial_path(m: @message.id)
      else
        redirect_to home_path
      end
  	else
  		render :new
  	end
  end

  private

  def message_params
    params.require(:message).permit(:message, :address, :owner_id)
  end
end

app/controllers/receives_controller.rb
class ReceivesController < ApplicationController
	layout "top"
  before_filter :authenticate_user!

  def index
  	@messages = current_user.messages.mails.order("id DESC")
  end

  def show
  	@message = current_user.messages.find(params[:id])
  end

  def notify
  end
  
  def list
    @notifications = current_user.messages.notifications.order("id DESC")
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
	layout "top"

  def show
  end
  
end

app/controllers/tutorial_controller.rb
class TutorialController < ApplicationController
	layout "top"
	
  def show
  end

  def confirm
  	@message = Message.find(params[:m])
  end

  def complete
  end
  
end

app/controllers/x/home_controller.rb
class X::HomeController < ApplicationController
	layout "application"
	before_filter :authenticate_admin!

  def show
  end
  
end

app/controllers/x/messages_controller.rb
class X::MessagesController < ApplicationController
	layout "application"
	before_filter :authenticate_admin!

  def index
  	@messages = Message.mails.order("id DESC")
  end

  def edit
  	setup_message
  	@q = User.search(params[:q])
	  @users = @q.result(distinct: true).order(:id)
  end

  def update
    setup_message
  end

  def connect
    setup_message
    users = User.find(params[:user_ids])
    @message.users << users
    redirect_to x_messages_path
  end

  private

  def setup_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:message, :address)
  end

end

app/controllers/x/notifications_controller.rb
class X::NotificationsController < ApplicationController
  layout "application"
  before_filter :authenticate_admin!
  
  def index
    @messages = Message.notifications.order("id DESC")
  end

  def show
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.reply_to = User.find(params[:reply_to]) if params[:reply_to].present?
    @message.users << User.all
    if @message.save
      redirect_to x_notifications_path
    else
      render :new
    end
  end

  def edit
    setup_message
  end

  def update
    setup_message
    if @message.update_attributes(message_params)
      redirect_to x_notifications_path
    else
      render :edit
    end
  end

  private

  def setup_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:message, :text, :reply_to)
  end

end

app/controllers/x/users_controller.rb
class X::UsersController < ApplicationController
	layout "application"
	before_filter :authenticate_admin!

  def index
  	@q = User.search(params[:q])
	  @users = @q.result(distinct: true).order(:id)
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/receives_helper.rb
module ReceivesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/x/home_helper.rb
module X::HomeHelper
end

app/helpers/x/messages_helper.rb
module X::MessagesHelper
end

app/helpers/x/notifications_helper.rb
module X::NotificationsHelper
end

app/helpers/x/users_helper.rb
module X::UsersHelper
end

app/views/home/show.html.erb
<div id="guide7" class="guide-component">
　　　　　　　　　　　
  <div class="button1">
    <a href="/receives"><span>サンプルテキスト</span></a>
  </div>

  <div class="button2">
    <a href="/messages/new"><span>サンプルテキスト</span></a>
  </div>

  <div class="button3">
    <a href="/receives/notify"><span>サンプルテキスト</span></a>
  </div>

</div>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

app/views/messages/new.html.erb
<section class="content">
<div class="row">
<div class="col-lg-12">
  <div class="portlet portlet-default">
    <div class="portlet-body">
    <%= form_for @message, :url => messages_path, html: { multipart: true } do |f| %>
      <%= render "common/error", object: @message %>
      <% if @sender %>
      <%= hidden_field_tag :sender, @sender.id %>
      <% else %>
      <div class="form-group">
        <span class="btn btn-block btn-success btn-lg btn-file">
          宛先を撮影する <%= f.file_field :address, accept: "image/*", capture: "camera" %>
        </span>
      </div>
      <% end %>
      <% if @reply.present? %>
        <%= hidden_field_tag :reply, @reply %>
      <% end %>
      <div class="form-group">
        <span class="btn btn-block btn-success btn-lg btn-file">
          本文を撮影する <%= f.file_field :message, accept: "image/*", capture: "camera" %>
        </span>
      </div>
      <%= f.submit "送信", data: { disable_with: "送信中" }, class: "btn btn-lg btn-block btn-primary" %>
    <% end %>
    <div class="clearfix"></div>
    </div>
  </div>
</div>
</div>
</section>

app/views/messages/show.html.erb
 <div class="row">
  <div class="col-md-12">
    <div class="box">
    <div class="box-header">
    <h3 class="box-title">メッセージ</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
    <% if message.address.present? %>
	<p><%= image_tag(@message.address.url, class: "img-responsive text-center", alt: "message") %></p>
    <% end %>
    <p><%= image_tag(@message.message.url, class: "img-responsive text-center", alt: "message") %></p>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
	  	<%= link_to "このメッセージに返信する", new_x_notification_path, class: "btn btn-lg btn-block btn-primary" %>
	  	<div class="clearfix"></div>
    </div>
    </div>
  </div>
</div>

app/views/x/home/show.html.erb
<h1>X::Home#show</h1>
<p>Find me in app/views/x/home/show.html.erb</p>

app/views/x/messages/edit.html.erb
 <div class="row">
  <div class="col-md-12">
    <div class="box">
    <div class="box-header">
    <h3 class="box-title">宛先紐付け</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
    	<div class="row">
	    	<div class="col-md-4">
	    	<p><%= image_tag(@message.address.try(:url), class: "img-responsive", alt: "message", width: "300px") %></p>
	  	  <p><%= image_tag(@message.message.url, class: "img-responsive", alt: "message", width: "300px") %></p>
	  	  </div>
	  	  <div class="col-md-8">
	  	  	<div class="row">
			  		<div class="col-md-12">
							<%= search_form_for @q, url: edit_x_message_path(@message) do |f| %>
							<div class="input-group input-group-lg">
								<%= f.text_field :name_or_address_or_group_cont, placeholder: "氏名もしくは住所もしくは地域", class: "form-control" %>
						    <span class="input-group-btn">
						    	<%= button_tag(type: 'submit', class: 'btn btn-default', name: nil) do %>
										<i class="fa fa-search"></i>
									<% end %>
						    </span>
						  </div>
						  <% end %>
					  </div>
			    </div>
					<br>
		<%= form_tag connect_x_message_path(@message) do %>
		      <table class="table table-striped">
		      <tr>
		      	<th class="col-lg-1 text-center"></th>
		        <th class="col-lg-2 text-center">氏名</th>
		        <th class="col-lg-2 text-center">地域</th>
		        <th class="col-lg-4 text-center">現住所</th>
		        <th class="col-lg-3 text-center">旧住所</th>
		      </tr>
		      <% @users.each do |user| %>
		      <tr>
		      	<td class="text-left">
				      <div class="checkbox">
		            <label><%= check_box_tag "user_ids[]", user.id %></label>
		          </div>
		      	</td>
		        <td class="text-left"><%= user.name %></td>
		        <td class="text-left"><%= user.group %></td>
		        <td class="text-left">
		        	〒<%= user.zipcode %><br>
		        	<%= user.address %>
		        </td>
		        <td class="text-left"><%= user.old_address %></td>
		      </tr>
		      <% end %>
		      </table>
		      <br>
    		  <div class="row">
				    <div class="col-xs-12">
				      <%= submit_tag "チェックした方々に送信する", class: 'btn btn-lg btn-block btn-primary', :name => nil %>
				    </div>
				  </div>
		    </div>
	  	</div>
		<% end %>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
    	
    </div>
    </div>
  </div>
</div>

app/views/x/messages/index.html.erb
 <div class="row">
  <div class="col-md-12">
    <div class="box">
    <div class="box-header">
    <h3 class="box-title"><i class="fa fa-envelope-o"></i> 手紙一覧</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
      <table class="table table-striped">
      <tr>
        <th class="col-lg-1 text-center"></th>
        <th class="col-lg-2 text-center">差出人</th>
        <th class="col-lg-4 text-center">手紙</th>
        <th class="col-lg-2 text-center">差出日時</th>
        <th class="col-lg-2 text-center"></th>
      </tr>
      <% @messages.each do |message| %>
      <% if message.users.blank? %>
      <tr>
        <td class="text-center v"><%= message.id %></td>
        <td class="text-left v"><%= message.owner.name %></td>
        <td class="text-center v">
        <% if message.address.present? %>
        <%= image_tag(message.address.url, class: "img-responsive", width: "300px", alt: "message") %>
        <% end %>
        </td>
        <td class="text-center v"><%= message.created_at.strftime("%Y-%m-%d %H:%H") %></td>
        <td class="text-center v">
        <%= link_to "宛先を紐付ける", edit_x_message_path(message), class: "btn btn-lg btn-block btn-primary" %>
        </td>
      </tr>
      <% end %>
      <% end %>
      </table>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
    </div>
    </div>
  </div>
</div>

app/views/x/notifications/edit.html.erb
<h1>X::Notifications#edit</h1>
<p>Find me in app/views/x/notifications/edit.html.erb</p>

app/views/x/notifications/index.html.erb
 <div class="row">
  <div class="col-md-12">
    <div class="box">
    <div class="box-header">
    <h3 class="box-title"><i class="fa fa-volume-up"></i> お知らせ一覧</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
    	<div class="pull-right">
	  	<%= link_to "新規通知を作成する", new_x_notification_path, class: "btn btn-lg btn-primary" %>
	  	</div>
	  	<div class="clearfix"></div>
	  	<br>
      <table class="table table-striped">
      <tr>
        <th class="col-lg-6 text-center">お知らせ内容</th>
        <th class="col-lg-2 text-center">通知日時</th>
        <th class="col-lg-6 text-center">返信先</th>
      </tr>
      <% @messages.each do |message| %>
      <tr>
        <td class="text-left"><%= message.text %></td>
        <td class="text-center"><%= message.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td class="text-center"><%= message.reply_to.try(:name) %></td>
      </tr>
      <% end %>
      </table>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
    </div>
    </div>
  </div>
</div>

app/views/x/notifications/new.html.erb
<div class="row">
<div class="col-lg-12">
  <div class="portlet portlet-default">
    <div class="portlet-body">
    <%= form_for @message, :url => x_notifications_path, html: { multipart: true } do |f| %>
      <%= render "common/error", object: @message %>
      <div class="form-group">
        <%= f.text_area :text, class: "form-control", rows: 10, placeholder: "メッセージを入力してください" %>
      </div>
      <div class="form-group">
        <%= select_tag :reply_to, options_for_select(User.options_for_select), 
              {prompt: "返信先を選択してください", class: "form-control"} %>
      </div>
      <%= f.submit "登録", data: { disable_with: "送信中" }, class: "btn btn-lg btn-block btn-primary" %>
    <% end %>
    <div class="clearfix"></div>
    </div>
  </div>
</div>
</div>

app/views/x/notifications/show.html.erb
<h1>X::Notifications#show</h1>
<p>Find me in app/views/x/notifications/show.html.erb</p>

app/views/x/users/index.html.erb
 <div class="row">
  <div class="col-md-12">
    <div class="box">
    <div class="box-header">
    <h3 class="box-title"><i class="fa fa-users"></i> 浪江町民一覧</h3>
    </div><!-- /.box-header -->
    <div class="box-body">

	    <div class="row">
    		<div class="col-md-6">
					<%= search_form_for @q, url: x_users_path do |f| %>
					<div class="input-group input-group-lg">
						<%= f.text_field :name_or_address_or_group_cont, placeholder: "氏名もしくは住所もしくは地域", class: "form-control" %>
				    <span class="input-group-btn">
				    	<%= button_tag(type: 'submit', class: 'btn btn-default', name: nil) do %>
								<i class="fa fa-search"></i>
							<% end %>
				    </span>
				  </div>
				  <% end %>
			  </div>
	    </div>

	    <br>
      <table class="table table-striped">
      <tr>
        <th class="col-lg-2 text-center">氏名</th>
        <th class="col-lg-1 text-center">地域</th>
        <th class="col-lg-4 text-center">現住所</th>
        <th class="col-lg-3 text-center">旧住所</th>
        <th class="col-lg-2 text-center">Email</th>
      </tr>
      <% @users.each do |user| %>
      <tr>
        <td class="text-left"><%= user.name %></td>
        <td class="text-left"><%= user.group %></td>
        <td class="text-left">〒<%= user.zipcode %> <%= user.address %></td>
        <td class="text-left"><%= user.old_address %></td>
        <td class="text-left"><%= user.email %></td>
      </tr>
      <% end %>
      </table>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
    </div>
    </div>
  </div>
</div>

app/views/x/users/show.html.erb
<h1>X::Users#show</h1>
<p>Find me in app/views/x/users/show.html.erb</p>