config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root :to => 'top#show'
  resource :top, controller: :top, only: :show
  resource :home, controller: :home, only: :show
  resources :messages, only: [:index, :show, :new, :create]
  resources :receives, only: [:index, :show] do
    get :notify, on: :collection
    get :list, on: :collection
  end
  resource :guides, only: :show do
    get :start, on: :collection
  end
  resource :tutorial, controller: :tutorial, only: :show do
    get :confirm, on: :collection
    get :complete, on: :collection
  end
  
  devise_for :admins
  namespace :x do
    resource :home, controller: :home, only: :show
    resources :users, only: [:index, :show]
    resources :notifications, only: [:index, :show, :new, :create, :edit, :update]
    resources :messages, only: [:index, :edit, :update] do
      post :connect, on: :member
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :owner, class_name: 'User', foreign_key: "owner_id"
	has_many :senders, :dependent => :destroy
	has_many :users, :through => :senders
	belongs_to :reply_to, class_name: 'User', foreign_key: "reply_to"

	mount_uploader :address, MessageUploader
	mount_uploader :message, MessageUploader

	scope :notifications, -> { where("text IS NOT NULL") }
	scope :mails, -> { where("message IS NOT NULL")}

end

app/models/sender.rb
class Sender < ActiveRecord::Base
	belongs_to :user
	belongs_to :message
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :own_messages, class_name: 'Message', foreign_key: "owner_id"
	has_many :senders, :dependent => :destroy
	has_many :messages, :through => :senders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.options_for_select
    User.order(:id).collect do |usr|
      [usr.name, usr.id]
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  private

  def layout_by_resource
    return "top" if devise_controller?
    return "application"
  end

  def after_sign_in_path_for(resource)
    return guides_path if resource.is_a?(User)
    return x_messages_path if resource.is_a?(Admin)
  end

  def after_sign_out_path_for(resource)
    reset_session
    return root_path if resource == :user
    return root_path if resource == :admin
  end

end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
	layout "top"
	before_filter :authenticate_user!

  def show
  end

  def start
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "top"
	before_filter :authenticate_user!

  def show
  	@notifications = current_user.messages.notifications.order("id DESC")
  	@messages = current_user.messages.mails.order("id DESC")
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	layout "top"
  before_filter :authenticate_user!

  def index
  end

  def show
    @message = Message.find(params[:id])
  end
  
  def new
  	@message = Message.new
    @sender = User.find(params[:owner]) if params[:owner]
    if params[:reply]
      @sender = User.find(params[:reply])
      @reply = true
    end
  end

  def create
  	@message = current_user.own_messages.new(message_params)
    @message.users << User.find(params[:sender]) if params[:sender]
  	if @message.save
      if params[:reply].present?
    		redirect_to confirm_tutorial_path(m: @message.id)
      else
        redirect_to home_path
      end
  	else
  		render :new
  	end
  end

  private

  def message_params
    params.require(:message).permit(:message, :address, :owner_id)
  end
end

app/controllers/receives_controller.rb
class ReceivesController < ApplicationController
	layout "top"
  before_filter :authenticate_user!

  def index
  	@messages = current_user.messages.mails.order("id DESC")
  end

  def show
  	@message = current_user.messages.find(params[:id])
  end

  def notify
  end
  
  def list
    @notifications = current_user.messages.notifications.order("id DESC")
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
	layout "top"

  def show
  end
  
end

app/controllers/tutorial_controller.rb
class TutorialController < ApplicationController
	layout "top"
	
  def show
  end

  def confirm
  	@message = Message.find(params[:m])
  end

  def complete
  end
  
end

app/controllers/x/home_controller.rb
class X::HomeController < ApplicationController
	layout "application"
	before_filter :authenticate_admin!

  def show
  end
  
end

app/controllers/x/users_controller.rb
class X::UsersController < ApplicationController
	layout "application"
	before_filter :authenticate_admin!

  def index
  	@q = User.search(params[:q])
	  @users = @q.result(distinct: true).order(:id)
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/receives_helper.rb
module ReceivesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/x/home_helper.rb
module X::HomeHelper
end

app/helpers/x/messages_helper.rb
module X::MessagesHelper
end

app/helpers/x/notifications_helper.rb
module X::NotificationsHelper
end

app/helpers/x/users_helper.rb
module X::UsersHelper
end

app/views/receives/index.html.erb
<div id="guide5" class="guide-component">
  <% @messages.each do |message| %>
    <% if message.address.present? %>
    <p><%= image_tag(message.address.url, class: "img-responsive", alt: "message") %></p>
    <% end %>
    <p><%= image_tag(message.message.url, class: "img-responsive", alt: "message") %></p>
    <p class="text-center font-big">[差出人] <%= message.owner.name %></p>
    <br>
    <div class="button">
    <a href="/messages/new?owner='<%= message.owner_id %>'"><span>サンプルテキスト</span></a>
    </div>
    <hr>
  <% end %>
</div>

app/views/receives/list.html.erb
 <div class="row">
  <div class="col-md-12">
    <div class="box">
    <div class="box-header">
    <h1>浪江町からのお知らせ</h1>
    </div><!-- /.box-header -->
    <div class="box-body">
      <% @notifications.each do |note| %>
      <div class="row">
        <div class="col-lg-8">
          <p class="font-big"><%= note.text %></p>
        </div>
        <div class="col-lg-4">
          <p class="font-big"><%= note.created_at.strftime("%Y-%d-%m %H:%M") %></p>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-lg-12">
          <%= link_to "このお知らせに返信する", new_message_path(reply: note.reply_to), class: "btn btn-lg btn-block btn-info" %>
        </div>
      </div>
      <hr>
      <% end %>
    </div><!-- /.box-body -->
    </div>
    <div class="box">
      <div class="box-body">
        <%= link_to "ログアウト", destroy_user_session_path, { method: :delete, class: "btn btn-lg btn-block btn-default" } %>
      </div>
    </div>
  </div>
</div>

app/views/receives/notify.html.erb
<div id="guide8" class="guide-component">
	　
	<div class="button1">
		<a href="/receives/list"><span>サンプルテキスト</span></a>
	</div>

	<div class="button2">
		<a href="/receives/list"><span>サンプルテキスト</span></a>
	</div>

	<div class="button3">
		<a href="/receives/list"><span>サンプルテキスト</span></a>
	</div>

	<div class="button4">
		<a href="/receives/list"><span>サンプルテキスト</span></a>
	</div>

</div>

app/views/receives/show.html.erb
<div id="guide5" class="guide-component">
　　　　　　　
	<%= image_tag(@message.message.url, class: "img-responsive", alt: "message") %>
	　
	<div class="button">
		<a href="/tutorial/complete"><span>サンプルテキスト</span></a>
	</div>

</div>

app/views/top/show.html.erb
<h1>Top#show</h1>
<p>Find me in app/views/top/show.html.erb</p>